version: "3.9"

services:
  server:
    container_name: cheburland-server
    image: cheburland-server
    build:
        context: .
        dockerfile: Dockerfile.server
        args:
          SERVER_PORT: ${SERVER_PORT}
    restart: always
    env_file:
      - .env
    ports:
        - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - postgres
    volumes:
      - ./packages/server:/app/packages/server
    networks:
      - cheburland

networks:
  cheburland:
    driver: bridge

volumes:
  pg-data:
  pg-admin-data:
