ARG NODE_VERSION=16
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY lerna.json .
COPY packages/server/package.json ./packages/server/package.json

RUN yarn lerna bootstrap

EXPOSE $SERVER_PORT

CMD ["yarn", "dev", "--scope=server"]
