version: "3.9"

services:
#    client:
#        container_name: prakticum-client
#        image: prakticum-client
#        build:
#            context: .
#            dockerfile: Dockerfile.client
#            args:
#              CLIENT_PORT: ${CLIENT_PORT}
#        restart: always
#        ports:
#            - "${CLIENT_PORT}:80"
#        environment:
#          - CLIENT_PORT=${CLIENT_PORT}
#          - SERVER_PORT=${SERVER_PORT}
    server:
        container_name: prakticum-server
        image: prakticum-server
        build:
            context: .
            dockerfile: Dockerfile.server.dev
            args:
              SERVER_PORT: ${SERVER_PORT}
        restart: always
        ports:
            - "${SERVER_PORT}:${SERVER_PORT}"
        environment:
          SERVER_PORT: ${SERVER_PORT}
        depends_on:
          - postgres
        volumes:
          - ./packages/server:/app/packages/server
        networks:
          - awesome
    postgres:
      image: postgres:14
      ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./tmp/pgdata:/var/lib/postgresql/data
      networks:
        - awesome
    pgadmin:
      image: dpage/pgadmin4:7.5
      restart: always
      ports:
        - "8080:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
        PGADMIN_LISTEN_PORT: 80
      volumes:
        - ./tmp/pgadmin:/var/lib/pgadmin
      depends_on:
        - postgres
      networks:
        - awesome
networks:
  awesome:
    driver: bridge
