version: "3.9"

services:
  postgres:
    container_name: cheburland-postgres
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - cheburland
  server:
    container_name: cheburland-server
    image: dksr/cheburland:latest
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    depends_on:
      - postgres
    volumes:
      - ./packages/server:/app/packages/server
    networks:
      - cheburland
  nginx:
    image: nginx:latest
    container_name: cheburland-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - cheburland
    depends_on:
      - server
networks:
  cheburland:
    driver: bridge

volumes:
  pg-data:
  pg-admin-data:
