version: "3.9"

services:
  server:
      container_name: cheburland-server
      image: cheburland-server
      build:
          context: .
          dockerfile: Dockerfile.server
          args:
            SERVER_PORT: ${SERVER_PORT}
      restart: always
      ports:
          - "${SERVER_PORT}:${SERVER_PORT}"
      environment:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      depends_on:
        - postgres
      volumes:
        - ./packages/server:/app/packages/server
      networks:
        - cheburland
  postgres:
    container_name: cheburland-postgres
    image: postgres:14
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - cheburland
  pgadmin:
    container_name: cheburland-pgadmin
    image: dpage/pgadmin4:7.5
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pg-admin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - cheburland
networks:
  cheburland:
    driver: bridge
volumes:
  pg-data:
  pg-admin-data:
